spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      model: always